#!/bin/bash
./jcom $1
classname=`awk -F. -v var="$1" 'BEGIN {print $1}'`
java -cp .:/home/lazily_installed_junit/lib/junit-4.12.jar:/home/lazily_installed_junit/lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore $classname