#!/bin/bash
javac  -cp /home/lazily_installed_junit/lib/junit-4.12.jar: $1
if [ -z ${1+x} ]; then
    echo "Please specify file name. For example : Sample.java"
    exit 1
fi
classname=`echo $1 | awk -F. '{print $1}'`
java -cp .:/home/lazily_installed_junit/lib/junit-4.12.jar:/home/lazily_installed_junit/lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore $classname